name: Build LWC
on: [ push, pull_request ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v6
      - name: Read versions
        id: versions
        run: echo "java=$(sed -n 's/^java = \"\(.*\)\"/\1/p' gradle/libs.versions.toml)" >> "$GITHUB_OUTPUT"
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: ${{ steps.versions.outputs.java }}
          cache: 'gradle'
      - name: Build
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: LWC
          path: "target/LWC-*.jar"
